version: "3"
services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    networks:
      - epig
    environment:
      - EPIG_PORT=${EPIG_PORT:-8000}
    depends_on:
      - epig
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  chromium-headless:
    container_name: chromium-headless
    hostname: chromium
    cap_add:
      - SYS_ADMIN
    build:
      context: ./chromium-headless/
    expose:
      - ${CDP_PORT}
    networks:
      - epig
    environment:
      - CDP_PORT=${CDP_PORT:-9222}
      - WIDTH=${WIDTH:-1200}
      - HEIGHT=${HEIGHT:-630}
  preview-generator:
    container_name: preview-generator
    hostname: preview-generator
    build:
      context: ./preview-generator/
    expose:
      - ${EPIG_PORT}
    networks:
      - epig
    depends_on:
      - chromium-headless
    environment:
      - CDP_HOST=${CDP_HOST:-chromium}
      - CDP_PORT=${CDP_PORT}
      - EPIG_PORT=${EPIG_PORT:-8000}
      - WIDTH=${WIDTH:-1200}
      - HEIGHT=${HEIGHT:-630}
      - EVENT_NAME=${EVENT_NAME:-load}
      - QS_ADDITIONAL=${QS_ADDITIONAL:-""}
      - LINK
networks:
  epig:

