version: "3"
services:
  chromium-headless:
    container_name: chromium-headless
    hostname: ${CDP_HOST}
    cap_add:
      - SYS_ADMIN
    build:
      context: ./chromium-headless/
    expose:
      - ${CDP_PORT}
    networks:
      - epig-network
    environment:
      - CDP_PORT=${CDP_PORT:-9222}
  preview-generator:
    container_name: preview-generator
    hostname: preview-generator
    build:
      context: ./preview-generator/
    expose:
      - ${EPIG_PORT}
    networks:
      - epig-network
    depends_on:
      - chromium-headless
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
      - PORT=${EPIG_PORT:-8000}
      - CDP_HOST=${CDP_HOST:-chromium}
      - CDP_PORT=${CDP_PORT}
      - WIDTH=${WIDTH:-1200}
      - HEIGHT=${HEIGHT:-630}
      - EVENT_NAME=${EVENT_NAME:-load}
      - QS=${QS:-""}
      - SITE_URL
      - USE_HEADERS
      - CACHE_URL
networks:
  epig-network:
