apiVersion: v1
kind: Service
metadata:
  labels:
    project: epig
    app: chromium-headless
  name: chromium-headless
spec:
  ports:
    - protocol: TCP
      port: 9222
      targetPort: 9222
  selector:
    app: chromium-headless
