apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: chromium-headless-cache
  name: chromium-headless-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
