kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    project: epig
    app: nginx
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx
