apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: epig
    app: preview-generator
  name: preview-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preview-generator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        project: epig
        app: preview-generator
    spec:
      containers:
        - name: preview-generator
          image: preview-generator:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: epig-config
          env:
            - name: CACHE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
          ports:
            - containerPort: 8000
          resources: { }
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 10
          securityContext:
            readOnlyRootFilesystem: false
      restartPolicy: Always
