apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ENV_NAME }}-chromium-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: chromium-headless
    app.kubernetes.io/instance: {{ .Values.ENV_NAME }}-chromium-headless
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.ENV_NAME }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chromium-headless
    app.kubernetes.io/instance: {{ .Values.ENV_NAME }}-chromium-headless
    #don't add app.kubernetes.io/version
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.ENV_NAME }}
  ports:
  - name: main
    port: {{ .Values.CHROMIUM_PORT }}
    targetPort: {{ .Values.CHROMIUM_PORT }}
    protocol: TCP
