{{ if ne .Values.ENV_NAME "local" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ENV_NAME }}-epig
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: epig
    app.kubernetes.io/instance: {{ .Values.ENV_NAME }}-epig
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.ENV_NAME }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    cert-manager.io/cluster-issuer: letsencrypt-staging #use letsencrypt-staging for testing
    acme.cert-manager.io/http01-edit-in-place: "true" #required otherwise ACME challenge can't be completed
spec:
  tls:
    - hosts:
      - {{ .Values.ENV_NAME }}-epig.k8s-01.konturlabs.com
      secretName: {{ .Values.ENV_NAME }}-epig-tls
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ENV_NAME }}-epig.k8s-01.konturlabs.com
      http:
        paths:
          - path: /active/preview.png
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ENV_NAME }}-epig
                port:
                  number: {{ .Values.PORT }}
{{ end }}
