kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.ENV_NAME }}-redis-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Values.ENV_NAME }}-redis-secret
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.ENV_NAME }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  password: {{ .Values.CACHE_PASSWORD }}
