kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine3.16
          args: [ "/usr/local/etc/redis/redis.conf", "--requirepass", $(CACHE_PASSWORD) ]
          env:
            - name: CACHE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /usr/local/etc/redis
              name: config
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: data
          emptyDir: { }
        - name: config
          configMap:
            name: redis-config
            items:
              - key: redis-config
                path: redis.conf
---
kind: Service
apiVersion: v1
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: redis
