apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: bitnami/redis:7.0
    env:
    - name: ALLOW_EMPTY_PASSWORD
      value: "yes"
    - name: REDIS_DISABLE_COMMANDS
      value: "FLUSHDB,FLUSHALL"
    ports:
    - containerPort: 6379
