ENV_NAME: dev
SITE_URL: https://test-apps-ninja02.konturlabs.com/active/
APP_ID: 'f29339bd-8049-41ae-9d6b-f726d8451894'
TIMEOUT: 9000
CACHE_TTL: 120
DEBUG: TRUE
DEFAULT_IMAGE_URL: "https://test-apps-ninja02.konturlabs.com/active/static/assets/preview_screenshot.png"

containers:
  chromium_headless:
    replicas: 1
    tag: "latest"
  preview_generator:
    replicas: 1
    tag: "latest"
  redis:
    replicas: 1
    tag: "7-alpine3.16"
